name: bn_c
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.0.3
  - numpy=1.24.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - networkx=3.1
  - jupyterlab=4.0.3
  - pyyaml=6.0
  - pip=23.2.1
  - pip:
      - pgmpy==0.1.23
      - openpyxl==3.1.2
